apiVersion: apps/v1
kind: Deployment
metadata:
  name: cambio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cambio-db
  template:
    metadata:
      labels:
        app: cambio-db
    spec:
      containers:
        - name: cambio-db
          image: mysql:8.0.28
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_USER
              value: "docker"
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "cambio_service"
          ports:
            - containerPort: 3308
---
apiVersion: v1
kind: Service
metadata:
  name: cambio-db-service
spec:
  ports:
    - port: 3308
      targetPort: 3308
  selector:
    app: cambio-db
