version: '3.4'
services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
    - 9411:9411
    networks:
    - felipe-network
  
  
  cambio-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: docker
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
    - 3308:3308
    expose:
    - 3308
    networks:
    - felipe-network
  
  
  book-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123M45
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
    - 3310:3310
    expose:
    - 3310
    networks:
    - felipe-network
  
  
  naming-server:
    image: felipedev21/naming-server:0.0.1-SNAPSHOT
    ports:
    - 8761:8761
    networks:
    - felipe-network
  
  
  api-gateway:
    image: felipedev21/api-gateway:0.0.1-SNAPSHOT
    ports:
    - 8765:8765
    depends_on:
    - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
    - felipe-network
  
  
  cambio-service:
    image: felipedev21/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http:/zipkin-server:9411/
      SPRING.APPLICATION.NAME: cambio-service
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&&serverTimeZone=UTC&TLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 12345
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&&serverTimeZone=UTC&TLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 12345
    ports:
    - 8000:8000
    depends_on:
    - naming-server
    - cambio-db
    networks:
    - felipe-network
    
    
  book-service:
    image: felipedev21/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http:/zipkin-server:9411/
      SPRING.APPLICATION.NAME: book-service
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&&serverTimeZone=UTC&TLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 12345
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&&serverTimeZone=UTC&TLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 12345
    ports:
    - 8100:8100
    depends_on:
    - naming-server
    - book-db
    networks:
    - felipe-network
    
    
networks:
  felipe-network:
    driver: bridge
    
    