version: '3.4'

services:
  naming-server:
    image: felipedev21/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - felipe-network
  zipkin:
    image: openzipkin/zipkin:2.23.3
    ports:
      - 9411:9411
    networks:
      - felipe-network

networks:
  felipe-network:
    driver: bridge