server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
      books:
        max-attempts: 3
        wait-duration: 1s
      book:
        max-attempts: 3
        wait-duration: 1s
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimeZone=true&serverTimeZone=UTC
    username: root
    password: 12345
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas:
    - book_service
    user: root
    password: 12345 
springdoc:
  api-docs:
    path: book-service/v3/api-docs
