spring:
  config:
    import: "optional:configserver:"
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Ciao"
  default-value: "Mondo"
